#
#===============================================================================
#
#         FILE:  Stylesheet.pod
#
#  DESCRIPTION:  
#
#       AUTHOR:  Andrey Kostenko (), <andrey@kostenko.name>
#      COMPANY:  Rambler Internet Holding
#      CREATED:  03.11.2009 15:44:37 MSK
#     REVISION:  ---
#===============================================================================


=head1 NAME

CSS::Croco::StyleSheet - stylesheet object

=head1 SYNOPSYS

    my $croco = CSS::Croco->new;
    my $stylesheet = $croco->parse( ' * { property: value }' );
    my $statements = $stylesheet->rules

=head1 METHODS

=head2 rules

Returns all CSS statements.


=cut

